version: '3.9'

services:
  webapi1: &webapi1
    hostname: webapi1
    container_name: api-service-1
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile
    depends_on: 
      - db
    restart: always      
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Username=postgres;Password=postgres;Database=rinha;No Reset On Close=true;Max Auto Prepare=10;Auto Prepare Min Usages=1;Pooling=true;Maximum Pool Size=50;
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "200MB"
  
  webapi2:
    <<: *webapi1
    hostname: webapi2
    container_name: api-service-2

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rinha
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "130MB"
    command: postgres -c max_connections=150

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: 
      - webapi1
      - webapi2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"